//! Build script for the architecture-neutral `analemma` core.
//!
//! Generates `src/table_generated.rs`: a numeric substitution table for
//! balanced-ternary words of `ANALEMMA_TRITS` trits.
//!
//! Supported widths:
//!   3, 6, 9  -> a static table of 3^N entries (`static TABLE`);
//!   18       -> no static table (3^18 = 387_420_489 entries would not fit
//!               into .rodata); instead a composite module is generated on
//!               top of the 6-trit table (three trytes per word).
//!
//! The core is architecture-neutral by design: no ISA, no opcodes,
//! no punched-tape frames, no charsets. Those live in architecture crates
//! that depend on this one.

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

const SUPPORTED: [usize; 4] = [3, 6, 9, 18];

fn pow3(n: usize) -> i64 {
    (0..n).fold(1i64, |acc, _| acc * 3)
}

fn main() {
    let trits: usize = env::var("ANALEMMA_TRITS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(6);
    assert!(
        SUPPORTED.contains(&trits),
        "ANALEMMA_TRITS must be one of {:?} (got {})",
        SUPPORTED, trits
    );

    println!("cargo:rustc-cfg=analemma_trits=\"{}\"", trits);
    println!("cargo:rustc-check-cfg=cfg(analemma_trits)");
    println!("cargo:rerun-if-env-changed=ANALEMMA_TRITS");

    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_path = Path::new(&manifest).join("src/table_generated.rs");
    let mut f = BufWriter::new(File::create(&out_path).unwrap());

    writeln!(f, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(
        f,
        "// Core width: {} trit(s). Architecture-neutral: no ISA, no tape, no charset.",
        trits
    )
    .unwrap();
    writeln!(f).unwrap();

    match trits {
        18 => {
            // Base table for composite access. Always 6 trits (the tryte):
            // a machine word of 18 trits is three trytes, historically and here.
            writeln!(f, "/// Base 6-trit (tryte) table used by the 18-trit composite layer.").unwrap();
            writeln!(f, "pub mod table6 {{").unwrap();
            emit_static_table(&mut f, 6);
            writeln!(f, "}}").unwrap();
            writeln!(f).unwrap();
            emit_composite18(&mut f);
        }
        n => emit_static_table(&mut f, n),
    }
}

// ============================================================================
// Static table (3 / 6 / 9 trits)
// ============================================================================

fn emit_static_table(f: &mut BufWriter<File>, n: usize) {
    let table_size = pow3(n) as usize;
    let offset: i32 = ((pow3(n) - 1) / 2) as i32;
    let nonary_len = (n + 1) / 2;

    writeln!(f, "/// Number of trits per word in this build.").unwrap();
    writeln!(f, "pub const TRITS: usize = {};", n).unwrap();
    writeln!(f, "/// Absolute value of the most negative representable value.").unwrap();
    writeln!(f, "pub const OFFSET: i32 = {};", offset).unwrap();
    writeln!(f, "/// Total number of distinct values: 3^TRITS.").unwrap();
    writeln!(f, "pub const TABLE_SIZE: usize = {};", table_size).unwrap();
    writeln!(f, "/// Whether `static TABLE` exists in this build (false for 18 trits).").unwrap();
    writeln!(f, "pub const HAS_STATIC_TABLE: bool = true;").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "#[derive(Clone, Copy, Debug)]").unwrap();
    writeln!(f, "pub struct Entry {{").unwrap();
        writeln!(f, "    /// Trit string, least significant first, e.g. \"ZPZZPN\".").unwrap();
        writeln!(f, "    pub str_trits: &'static str,").unwrap();
        writeln!(f, "    /// Balanced nonary string, most significant digit first, e.g. \"Y03\".").unwrap();
        writeln!(f, "    pub str_nonary: &'static str,").unwrap();
        writeln!(f, "    /// Absolute value in binary, e.g. \"10011111\".").unwrap();
        writeln!(f, "    pub str_abs_binary: &'static str,").unwrap();
        writeln!(f, "    /// Value as 32-bit two's complement, e.g. \"11111111111111111111111101100001\".").unwrap();
        writeln!(f, "    pub str_signed_binary: &'static str,").unwrap();
        writeln!(f, "    /// Absolute value in decimal.").unwrap();
        writeln!(f, "    pub str_abs_decimal: &'static str,").unwrap();
        writeln!(f, "    /// Signed value in decimal.").unwrap();
        writeln!(f, "    pub str_signed_decimal: &'static str,").unwrap();
        writeln!(f, "    /// Absolute value in upper-case hex.").unwrap();
        writeln!(f, "    pub str_abs_hex: &'static str,").unwrap();
        writeln!(f, "    /// Value as 32-bit two's complement in hex, e.g. \"FFFFFF61\".").unwrap();
    writeln!(f, "    pub str_signed_hex: &'static str,").unwrap();
    writeln!(f, "    /// Signed value in the balanced range -(OFFSET)..=+OFFSET.").unwrap();
    writeln!(f, "    pub value: i32,").unwrap();
    writeln!(f, "    /// Absolute value as u32.").unwrap();
    writeln!(f, "    pub abs_binary: u32,").unwrap();
    writeln!(f, "    /// Signed value (same as `value`).").unwrap();
    writeln!(f, "    pub signed_binary: i32,").unwrap();
    writeln!(f, "    /// Trits, least significant first.").unwrap();
    writeln!(f, "    pub trits: [crate::trit::Trit; {}],", n).unwrap();
    writeln!(f, "    /// Balanced nonary digits, most significant first (pairs of trits).").unwrap();
    writeln!(f, "    pub nonary_digits: [i8; {}],", nonary_len).unwrap();
    writeln!(f, "    /// Index of the most significant nonzero trit (−1 if zero);").unwrap();
    writeln!(f, "    /// for sign checks and converters.").unwrap();
    writeln!(f, "    pub top_nonzero: i8,").unwrap();
    writeln!(f, "    /// Parity of the value (even ↔ an even count of nonzero").unwrap();
    writeln!(f, "    /// trits, since 3 ≡ 1 mod 2).").unwrap();
    writeln!(f, "    pub is_even: bool,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "pub static TABLE: [Entry; TABLE_SIZE] = [").unwrap();
    for v in -offset..=offset {
        let trits = value_to_trits(v, n);
        let digits = nonary_digits(&trits);
        let trit_name = |t: i8| match t { -1 => "N", 0 => "Z", 1 => "P", _ => unreachable!() };

        writeln!(f, "    Entry {{").unwrap();
            writeln!(f, "        str_trits: {:?},", trits_to_string(&trits)).unwrap();
            writeln!(f, "        str_nonary: {:?},", nonary_to_string(&digits)).unwrap();
            writeln!(f, "        str_abs_binary: {:?},", format!("{:b}", v.unsigned_abs())).unwrap();
            writeln!(f, "        str_signed_binary: {:?},", format!("{:032b}", v as u32)).unwrap();
            writeln!(f, "        str_abs_decimal: {:?},", format!("{}", v.unsigned_abs())).unwrap();
            writeln!(f, "        str_signed_decimal: {:?},", format!("{}", v)).unwrap();
            writeln!(f, "        str_abs_hex: {:?},", format!("{:X}", v.unsigned_abs())).unwrap();
        writeln!(f, "        str_signed_hex: {:?},", format!("{:08X}", v as u32)).unwrap();
        writeln!(f, "        value: {},", v).unwrap();
        writeln!(f, "        abs_binary: {},", v.unsigned_abs()).unwrap();
        writeln!(f, "        signed_binary: {},", v).unwrap();
        writeln!(f, "        trits: [").unwrap();
        for &t in &trits {
            writeln!(f, "            crate::trit::Trit::{},", trit_name(t)).unwrap();
        }
        writeln!(f, "        ],").unwrap();
        writeln!(f, "        nonary_digits: {:?},", digits).unwrap();
        let top_nonzero = trits.iter().rposition(|&t| t != 0).map(|i| i as i8).unwrap_or(-1);
        writeln!(f, "        top_nonzero: {},", top_nonzero).unwrap();
        let nz = trits.iter().filter(|&&t| t != 0).count();
        writeln!(f, "        is_even: {},", nz % 2 == 0).unwrap();
        writeln!(f, "    }},").unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "#[inline(always)]").unwrap();
    writeln!(f, "pub fn entry_by_value(value: i32) -> Option<&'static Entry> {{").unwrap();
    writeln!(f, "    if (-OFFSET..=OFFSET).contains(&value) {{").unwrap();
    writeln!(f, "        Some(&TABLE[(value + OFFSET) as usize])").unwrap();
    writeln!(f, "    }} else {{").unwrap();
    writeln!(f, "        None").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "#[inline(always)]").unwrap();
    writeln!(f, "pub fn entry_by_trits(trits: &[crate::trit::Trit; TRITS]) -> Option<&'static Entry> {{").unwrap();
    writeln!(f, "    let mut value: i32 = 0;").unwrap();
    writeln!(f, "    let mut pow: i32 = 1;").unwrap();
    writeln!(f, "    for i in 0..TRITS {{").unwrap();
    writeln!(f, "        value += trits[i].to_i8() as i32 * pow;").unwrap();
    writeln!(f, "        pow *= 3;").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "    entry_by_value(value)").unwrap();
    writeln!(f, "}}").unwrap();
}

// ============================================================================
// Composite 18-trit layer (no static table)
// ============================================================================

fn emit_composite18(f: &mut BufWriter<File>) {
    writeln!(f, "/// An 18-trit word, composed of three 6-trit trytes.").unwrap();
    writeln!(f, "///").unwrap();
    writeln!(f, "/// There is deliberately no `static TABLE` here: 3^18 = 387_420_489").unwrap();
    writeln!(f, "/// entries would not fit into .rodata. Every accessor composes three").unwrap();
    writeln!(f, "/// lookups into `table6` instead.").unwrap();
    writeln!(f, "pub const TRITS: usize = 18;").unwrap();
    writeln!(f, "pub const OFFSET: i32 = 193_710_244;").unwrap();
    writeln!(f, "pub const TABLE_SIZE: usize = 387_420_489;").unwrap();
    writeln!(f, "pub const HAS_STATIC_TABLE: bool = false;").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "#[derive(Clone, Copy, Debug)]").unwrap();
    writeln!(f, "pub struct Entry {{").unwrap();
    writeln!(f, "    pub value: i32,").unwrap();
    writeln!(f, "    pub abs_binary: u32,").unwrap();
    writeln!(f, "    pub signed_binary: i32,").unwrap();
    writeln!(f, "    pub trits: [crate::trit::Trit; 18],").unwrap();
    writeln!(f, "    pub nonary_digits: [i8; 9],").unwrap();
    writeln!(f, "    pub trytes: (table6::Entry, table6::Entry, table6::Entry),").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    // Built on demand: no static table exists for 18 trits, so strings are
    // composed from the numeric fields (and from per-tryte strings via
    // `entry.trytes.*` where finer detail is needed).
    const DISPLAY18: &str = r#"impl std::fmt::Display for Entry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use crate::trit::Trit;
        let trits: String = self.trits.iter().rev().map(|t| match t {
            Trit::N => 'N', Trit::Z => 'Z', Trit::P => 'P',
        }).collect();
        let nonary: String = self.nonary_digits.iter().map(|&d| match d {
            -4 => 'W', -3 => 'Y', -2 => 'X', -1 => 'Z',
            0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4',
            _ => '?',
        }).collect();
        write!(f, "Entry18(value={}, trits={}, nonary={}, hex={:08X})",
               self.value, trits, nonary, self.value as u32)
    }
}"#;
    writeln!(f, "{}", DISPLAY18).unwrap();
    writeln!(f).unwrap();

    writeln!(f, "#[inline]").unwrap();
    writeln!(f, "pub fn entry_by_value(value: i32) -> Option<Entry> {{").unwrap();
    writeln!(f, "    if !(-OFFSET..=OFFSET).contains(&value) {{").unwrap();
    writeln!(f, "        return None;").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "    // code = value + OFFSET decomposes uniquely into three tryte codes:").unwrap();
    writeln!(f, "    //   value = (hi - 364) * 3^12 + (mid - 364) * 3^6 + (lo - 364)").unwrap();
    writeln!(f, "    let code = (value + OFFSET) as u32;").unwrap();
    writeln!(f, "    let lo = table6::entry_by_value((code % 729) as i32 - 364)?;").unwrap();
    writeln!(f, "    let mid = table6::entry_by_value(((code / 729) % 729) as i32 - 364)?;").unwrap();
    writeln!(f, "    let hi = table6::entry_by_value((code / 531_441) as i32 - 364)?;").unwrap();
    writeln!(f, "    let mut trits = [crate::trit::Trit::Z; 18];").unwrap();
    writeln!(f, "    trits[..6].copy_from_slice(&lo.trits);").unwrap();
    writeln!(f, "    trits[6..12].copy_from_slice(&mid.trits);").unwrap();
    writeln!(f, "    trits[12..].copy_from_slice(&hi.trits);").unwrap();
    writeln!(f, "    // MSB first: high tryte digits, then mid, then low.").unwrap();
    writeln!(f, "    let mut nonary_digits = [0i8; 9];").unwrap();
    writeln!(f, "    nonary_digits[..3].copy_from_slice(&hi.nonary_digits);").unwrap();
    writeln!(f, "    nonary_digits[3..6].copy_from_slice(&mid.nonary_digits);").unwrap();
    writeln!(f, "    nonary_digits[6..].copy_from_slice(&lo.nonary_digits);").unwrap();
    writeln!(f, "    Some(Entry {{").unwrap();
    writeln!(f, "        value,").unwrap();
    writeln!(f, "        abs_binary: value.unsigned_abs(),").unwrap();
    writeln!(f, "        signed_binary: value,").unwrap();
    writeln!(f, "        trits,").unwrap();
    writeln!(f, "        nonary_digits,").unwrap();
    writeln!(f, "        trytes: (*lo, *mid, *hi),").unwrap();
    writeln!(f, "    }})").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "#[inline]").unwrap();
    writeln!(f, "pub fn entry_by_trits(trits: &[crate::trit::Trit; 18]) -> Option<Entry> {{").unwrap();
    writeln!(f, "    let mut value: i32 = 0;").unwrap();
    writeln!(f, "    let mut pow: i32 = 1;").unwrap();
    writeln!(f, "    for i in 0..18 {{").unwrap();
    writeln!(f, "        value += trits[i].to_i8() as i32 * pow;").unwrap();
    writeln!(f, "        pow *= 3;").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "    entry_by_value(value)").unwrap();
    writeln!(f, "}}").unwrap();
}

// ============================================================================
// Helpers
// ============================================================================

/// Balanced representation: v = sum(trits[i] * 3^i), trits[i] in {-1, 0, +1}.
fn value_to_trits(v: i32, n: usize) -> Vec<i8> {
    let mut trits = vec![0i8; n];
    let mut temp = v;
    for i in 0..n {
        let rem = temp.rem_euclid(3) as i8;
        trits[i] = if rem == 2 { -1 } else { rem };
        temp = (temp - trits[i] as i32) / 3;
    }
    trits
}

/// Balanced nonary digits, most significant first.
/// Pairs are anchored at the least significant end: (t1,t0), (t3,t2), ...
/// An odd leading trit forms the most significant digit alone.
fn nonary_digits(trits: &[i8]) -> Vec<i8> {
    let mut ds = Vec::with_capacity((trits.len() + 1) / 2);
    let mut j = 0;
    while j < trits.len() {
        if j + 1 < trits.len() {
            ds.push(trits[j + 1] * 3 + trits[j]);
            j += 2;
        } else {
            ds.push(trits[j]);
            j += 1;
        }
    }
    ds.reverse();
    ds
}

fn trits_to_string(trits: &[i8]) -> String {
    trits.iter().map(|&t| match t { -1 => 'N', 0 => 'Z', 1 => 'P', _ => '?' }).collect()
}

fn nonary_to_string(ds: &[i8]) -> String {
    // Glyph order per the Setun-70 architecture description (§6.1):
    // W, X, Y, Z, 0..=4 for digit values -4..=4.
    ds.iter().map(|&d| match d {
        -4 => 'W', -3 => 'X', -2 => 'Y', -1 => 'Z',
        0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4',
        _ => '?',
    }).collect()
}
